name: Demo Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # specify your project's Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Dummy Build Step
        run: echo "Building project..."
        env:
          CI: true

      - name: Run Dummy Tests
        run: |
          echo "Running test 1 - Passed"
          echo "Running test 2 - Passed"
          echo "Running test 3 - Passed"

      - name: Dummy Code Analysis
        run: echo "Code analysis completed without issues."
