name: Flutter Build & Test


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test Flutter App
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Flutter SDK
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # Use the version you're working with locally

      # Step 3: Cache Flutter dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter

      # Step 4: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 5: Run tests (continue on warnings, but fail on test failures)
      - name: Run Flutter tests
        run: flutter test
